server:
  port: 9282

mybatis-plus:
  #XML文件扫描
  mapper-locations: classpath*:/mapper/cloudopen/*.xml
  # 配置日志
  configuration:
    map-underscore-to-camel-case: false # 数据库下划线自动转驼峰标示关闭
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 这个配置会将执行的sql打印出来，这个可以存放在文件中 StdOutImpl的是只能打印到控制台
    #log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl



spring:
  datasource:
    dynamic:
      primary: mysql #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        mysql:
          url: jdbc:mysql://127.0.0.1/cloud_open?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 1234abcd
#        mysql_2:
#          url: jdbc:mysql://192.168.85.64/area?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          username: root
#          password: 123456


  #热部署
  devtools:
    restart:
      #需要实时更新的目录
      additional-paths: /resources/**,/java/com/wyj/cloudopen/controller/**
      enabled: true
